# Generated by Django 4.1.3 on 2022-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_video/', verbose_name='Постер курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dscription',
            field=models.TextField(max_length=255, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='course_iamges/', verbose_name='Постер курса'),
        ),
    ]
