# Generated by Django 4.1.3 on 2022-11-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dscription',
            new_name='description',
        ),
    ]
