# Generated by Django 4.1.3 on 2022-11-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя выпусника')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление выпусника')),
                ('place_of_work', models.CharField(max_length=50, verbose_name='Место работы')),
                ('location', models.CharField(max_length=50, verbose_name='Город')),
                ('salary', models.CharField(max_length=50, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Выпусник',
                'verbose_name_plural': 'Выпусники',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.CharField(max_length=255, verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='response_status',
            field=models.BooleanField(default=False, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='response',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Направление заявки'),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя заявки'),
        ),
        migrations.AlterField(
            model_name='response',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер заявки'),
        ),
    ]
