# Generated by Django 4.1.3 on 2022-11-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_settings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'Галларея',
                'verbose_name_plural': 'Галларея',
            },
        ),
    ]
