# Generated by Django 4.1.3 on 2022-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='course',
            field=models.CharField(default=1, max_length=255, verbose_name='Курс отзыва'),
            preserve_default=False,
        ),
    ]
