# Generated by Django 4.1.3 on 2022-11-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_reviews_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduates',
            name='image',
            field=models.FileField(default=1, upload_to='graduate_image/', verbose_name='Фото выпусника'),
            preserve_default=False,
        ),
    ]
