# Generated by Django 4.1.3 on 2022-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_graduates_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduates2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя выпусника')),
                ('image', models.FileField(upload_to='graduate_image/', verbose_name='Фото выпусника')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление выпусника')),
                ('link_to_project', models.URLField(max_length=50, verbose_name='Ссылка на проект')),
                ('video_project', models.FileField(upload_to='vidro_project/', verbose_name='Видео выпусника')),
            ],
            options={
                'verbose_name': 'Выпусник2',
                'verbose_name_plural': 'Выпусники2',
            },
        ),
    ]
