# Generated by Django 4.1.3 on 2022-11-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_graduates2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduates',
        ),
        migrations.DeleteModel(
            name='Graduates2',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв выпусника', 'verbose_name_plural': 'Отзывы выпусников'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default=1, upload_to='review_iamge/', verbose_name='Фото выпусника'),
            preserve_default=False,
        ),
    ]
