# Generated by Django 4.1.3 on 2022-11-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram'),
        ),
    ]
