# Generated by Django 4.1.3 on 2022-11-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='whatsapp'),
        ),
    ]
