# Generated by Django 4.1.3 on 2022-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teacher_facebook_teacher_instagram_teacher_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='video',
            field=models.FileField(default=1, upload_to='team_videos/', verbose_name='Видео учителя'),
            preserve_default=False,
        ),
    ]
