# Generated by Django 4.1.3 on 2022-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teacher_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='whatsapp'),
        ),
    ]
