# Generated by Django 4.1.3 on 2022-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teacher_telegram_alter_teacher_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Об учителе'),
            preserve_default=False,
        ),
    ]
